In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn import preprocessing
import sys
import matplotlib.pyplot as plt
%matplotlib inline

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:
data = pd.read_excel("preliminary_118by127.xlsx")
data.head()

,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
0,NaN,Nr.,Lit.,Bez.,Einheiten E,Querschnittswerte - Section properties,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,b\nb,bw\nbw,h\nh,hf\nhf,"hh,top\nhh,top",...,"fcm,cyl\nfcm_cyl",fck\nfck,f´c\nfc_prime,Vct_ACI,Vs_ACI,Vcal_sACI,Vmax_ACI,rat_smax,VACI_cal,gmod_ACI
2,NaN,Nr.,Lit.,Bez.,Einheiten E,NaN,NaN,NaN,NaN,NaN,...,"fcm,cyl\nfcm_cyl",fck\nfck,f´c\nfc_prime,Vct_ACI,Vs_ACI,Vcal_sACI,Vmax_ACI,rat_smax,VACI_cal,gmod_ACI
3,NaN,-,-,-,SI / A,mm,mm,mm,mm,mm,...,MPa,MPa,MPa,kN,kN,kN,kN,NaN,kN,NaN
4,Ahmad_1996_003_NNW-3,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286

In [3]:
data.info

<bound method DataFrame.info of                         1    2                 3      4            5    \
0                       NaN  Nr.              Lit.   Bez.  Einheiten E
1                       NaN  NaN               NaN    NaN          NaN
2                       NaN  Nr.              Lit.   Bez.  Einheiten E
3                       NaN    -                 -      -       SI / A
4      Ahmad_1996_003_NNW-3   19            Ahmad;  NNW-3            A
..                      ...  ...               ...    ...          ...
112    Ozcebe_1999_009_TS36  559               NaN   TS36           SI
113    Ozcebe_1999_011_TH39  561               NaN   TH39           SI
114    Ozcebe_1999_012_TS39  562               NaN   TS39           SI
115   Petersson_1972_001_V1  564  Petersson (1972)     V1           SI
116  Petersson_1972_002_VL1  565               NaN    VL1           SI

                                        6       7      8       9    \
0    Querschnittswerte - Section properties     NaN    NaN     NaN
1                                      b\nb  bw\nbw   h\nh  hf\nhf
2                                       NaN     NaN    NaN     NaN
3                                        mm      mm     mm      mm
4                                     127,0   127,0  254,0     NaN
..                                      ...     ...    ...     ...
112                                   150,0   150,0  360,0     NaN
113                                   150,0   150,0  360,0     NaN
114                                   150,0   150,0  360,0     NaN
115                                   175,0   175,0  353,0     NaN
116                                   301,0   120,0  307,0    63,0

                10   ...               118       119            120      121  \
0               NaN  ...               NaN       NaN            NaN      NaN
1    hh,top\nhh,top  ...  fcm,cyl\nfcm_cyl  fck\nfck  f´c\nfc_prime  Vct_ACI
2               NaN  ...  fcm,cyl\nfcm_cyl  fck\nfck  f´c\nfc_prime  Vct_ACI
3                mm  ...               MPa       MPa            MPa       kN
4               NaN  ...              41,5      37,5           39,1    26,82
..              ...  ...               ...       ...            ...      ...
112             NaN  ...              75,0      71,0           72,6    65,81
113             NaN  ...              73,0      69,0           70,6    64,89
114             NaN  ...              73,0      69,0           70,6    64,89
115             NaN  ...              38,0      34,0           35,6    55,84
116             NaN  ...              43,0      39,0           40,6    35,30

        122        123       124       125       126       127
0       NaN        NaN       NaN       NaN       NaN       NaN
1    Vs_ACI  Vcal_sACI  Vmax_ACI  rat_smax  VACI_cal  gmod_ACI
2    Vs_ACI  Vcal_sACI  Vmax_ACI  rat_smax  VACI_cal  gmod_ACI
3        kN         kN        kN       NaN        kN       NaN
4     41,06      67,88    134,08     0,506     67,88      1286
..      ...        ...       ...       ...       ...       ...
112   28,38      94,19    329,03     0,286     94,19      1655
113   24,83      89,73    324,47     0,277     89,73      1593
114   33,11      98,01    324,47     0,302     98,01      1828
115   39,21      95,05    279,21     0,340     95,05      1062
116  102,29     137,59    176,52     0,779    137,59      1386

[117 rows x 127 columns]>

In [4]:
data_mod = data[4:]

In [5]:
data_mod.head()

,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
4,Ahmad_1996_003_NNW-3,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286
5,Ahmad_1996_006_NHW-3,22,Xie;,NHW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"100,2","96,2","97,8","41,32","41,06","82,39","206,62","0,399","82,39",1245
6,Ahmad_1996_007_NHW-3a,23,Yu (1996),NHW-3a,A,"127,0","127,0","254,0",NaN,NaN,...,"91,8","87,8","89,4","39,51","53,38","92,89","197,53","0,470","92,89",1168
7,Ahmad_1996_008_NHW-3b,24,NaN,NHW-3b,A,"127,0","127,0","254,0",NaN,NaN,...,"105,3","101,3","102,9","42,38","64,05","106,44","211,92","0,502","106,44",1154
8,Ahmad_1996_009_NHW-4,25,NaN,NHW-4,A,"127,0","127,0","254,0",NaN,NaN,...,"100,8","96,8","98,4","41,45","41,06","82,51","207,26","0,398","82,51",1140

[Dummy Variables & One Hot Encoding]("https://medium.com/@subashdhoni86/dummy-variables-one-hot-encoding-ebf4f0391a2")

In [6]:
#dummies_authors = pd.get_dummies(data_mod[[1]])

In [7]:
#dummies_authors

In [8]:
data_mod[[1]].size

113

In [9]:
data_mod[[1]].info

<bound method DataFrame.info of                           1
4      Ahmad_1996_003_NNW-3
5      Ahmad_1996_006_NHW-3
6     Ahmad_1996_007_NHW-3a
7     Ahmad_1996_008_NHW-3b
8      Ahmad_1996_009_NHW-4
..                      ...
112    Ozcebe_1999_009_TS36
113    Ozcebe_1999_011_TH39
114    Ozcebe_1999_012_TS39
115   Petersson_1972_001_V1
116  Petersson_1972_002_VL1

[113 rows x 1 columns]>

In [10]:
# np_unique_authors = pd.unique(author_list)
#np_unique_authors

In [11]:
#https://stackoverflow.com/questions/50258960/how-to-apply-labelencoder-for-a-specific-column-in-pandas-dataframe

# df_new

In [12]:
# df_author = data_mod
# df_author[df_author[1][df_author[1]=="Ahmad_1996_003_NNW-3"] = author_list["Ahmad_1996_003_NNW-3"]]
# df_author

In [13]:
#trans_list = [1,3,4]

In [14]:
def myOHE(df, header):
    #df_list = df[header].values.tolist()
    #df_list = [str(val) for val in df[header].values]
    df_list = df[header].astype(str).tolist()
    myDict = {k:df_list.index(k) for k in df_list}
    #print (myDict)
    df_new = df
    le = preprocessing.LabelEncoder()
    df_new[header] = le.fit_transform(df_new[header].astype(str))
    # for head in myDict.keys():
    #     df_new[df_new[header]==head][head] = myDict[head]
    return df_new
# author_list = data_mod[1].values.tolist()
# df_new = data_mod
# le = preprocessing.LabelEncoder()
# df_new[1] = le.fit_transform(df_new[1].values)
# author_dict = {k:author_list.index(k) for k in author_list }
# for header in author_dict.keys():
#     df_new[df_new[1]==header][header] = author_dict[header]
# df_new

In [15]:
oneHotEncodeColumns = [1, 3, 4,5]

In [16]:
# df_new = myOHE(data_mod, 1)
df_new = data_mod
for col in oneHotEncodeColumns:
    df_new = myOHE(df_new, col)

/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_30737/2839377994.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[header] = le.fit_transform(df_new[header].astype(str))
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_30737/2839377994.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[header] = le.fit_transform(df_new[header].astype(str))
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_30737/2839377994.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[header] = le.fit_transform(df_new[header].astype(str))
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_30737/2839377994.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[header] = le.fit_transform(df_new[header].astype(str))

df_new

In [18]:
# for header in author_list[0]:
#     i = 0
#     ct = ColumnTransformer([header, OneHotEncoder(), [i]])#, remainder=’passthrough’)
#     print(data_mod[1].values)
#     X = data_mod[1].values
#     X = ct.fit_transform(X)
#     i+=1
#     print (X)

In [19]:
# data_mod[1] = data_mod[1][author_dict[data_mod[1]]]

In [20]:
# df_new.dropna?

# Python Pandas Decimal Mark EU to US

https://stackoverflow.com/questions/17531313/python-pandas-decimal-mark-eu-to-us

In [21]:
df_dropped = df_new.dropna(axis=1)
df_dropped

,1,2,3,4,5,6,7,8,15,16,...,118,119,120,121,122,123,124,125,126,127
4,0,19,2,40,0,"127,0","127,0","254,0",32258,"127,0",...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286
5,1,22,35,36,0,"127,0","127,0","254,0",32258,"127,0",...,"100,2","96,2","97,8","41,32","41,06","82,39","206,62","0,399","82,39",1245
6,2,23,36,37,0,"127,0","127,0","254,0",32258,"127,0",...,"91,8","87,8","89,4","39,51","53,38","92,89","197,53","0,470","92,89",1168
7,3,24,38,38,0,"127,0","127,0","254,0",32258,"127,0",...,"105,3","101,3","102,9","42,38","64,05","106,44","211,92","0,502","106,44",1154
8,4,25,38,39,0,"127,0","127,0","254,0",32258,"127,0",...,"100,8","96,8","98,4","41,45","41,06","82,51","207,26","0,398","82,51",1140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,105,559,38,105,1,"150,0","150,0","360,0",54000,"180,0",...,"75,0","71,0","72,6","65,81","28,38","94,19","329,03","0,286","94,19",1655
113,106,561,38,104,1,"150,0","150,0","360,0",54000,"180,0",...,"73,0","69,0","70,6","64,89","24,83","89,73","324,47","0,277","89,73",1593
114,107,562,38,106,1,"150,0","150,0","360,0",54000,"180,0",...,"73,0","69,0","70,6","64,89","33,11","98,01","324,47","0,302","98,01",1828
115,108,564,30,110,1,"175,0","175,0","353,0",61775,"176,5",...,"38,0","34,0","35,6","55,84","39,21","95,05","279,21","0,340","95,05",1062
116,109,565,38,112,1,"301,0","120,0","307,0",60732,"151,9",...,"43,0","39,0","40,6","35,30","102,29","137,59","176,52","0,779","137,59",1386

In [22]:
# list_val = [str(val) for val in df_dropped[4].values]
# list_val

In [23]:
# df_dropped[4].unique()

In [24]:
# samp_auth = preprocessing.LabelEncoder().fit_transform(df_dropped[4].astype(str))
# samp_auth

In [25]:
# samp_auth.size

In [26]:
df_exp = df_dropped

In [27]:
# df_final = df_dropped[[:4]]
# df_final

In [28]:
scaler = StandardScaler()
standardized_features = scaler.fit_transform(df_exp)

n_components = 2
pca = PCA(n_components=n_components)
principal_components = pca.fit_transform(standardized_features)
pc_df = pd.DataFrame(data=principal_components, columns=[f'PC{i+1}' for i in range(n_components)])

plt.figure(figsize=(8,6))
plt.scatter(pc_df['PC1'], pc_df['PC2'])
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA of Dataset')
plt.show()

explained_variance = pca.explained_variance_ratio_
print(f'Explained variance by component: {explained_variance}')

ValueError: could not convert string to float: '127,0'