In [177]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline

In [155]:
data = pd.read_excel("preliminary.xlsx")
data.head()

,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
0,NaN,Nr.,Lit.,Bez.,Einheiten E,Querschnittswerte - Section properties,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,b\nb,bw\nbw,h\nh,hf\nhf,"hh,top\nhh,top",...,"fcm,cyl\nfcm_cyl",fck\nfck,f´c\nfc_prime,Vct_ACI,Vs_ACI,Vcal_sACI,Vmax_ACI,rat_smax,VACI_cal,gmod_ACI
2,author,Nr.,Lit.,Bez.,Einheiten E,NaN,NaN,NaN,NaN,NaN,...,"fcm,cyl\nfcm_cyl",fck\nfck,f´c\nfc_prime,Vct_ACI,Vs_ACI,Vcal_sACI,Vmax_ACI,rat_smax,VACI_cal,gmod_ACI
3,NaN,-,-,-,SI / A,mm,mm,mm,mm,mm,...,MPa,MPa,MPa,kN,kN,kN,kN,NaN,kN,NaN
4,Ahmad_1996_003_NNW-3,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286

In [156]:
data.info

<bound method DataFrame.info of                         1    2       3       4            5    \
0                       NaN  Nr.    Lit.    Bez.  Einheiten E
1                       NaN  NaN     NaN     NaN          NaN
2                    author  Nr.    Lit.    Bez.  Einheiten E
3                       NaN    -       -       -       SI / A
4      Ahmad_1996_003_NNW-3   19  Ahmad;   NNW-3            A
..                      ...  ...     ...     ...          ...
76   Krefeld_1966_018_29d-2  428     NaN   29d-2            A
77   Krefeld_1966_020_29f-2  430     NaN   29f-2            A
78   Krefeld_1966_021_29g-2  431     NaN   29g-2            A
79  Krefeld_1966_024_24.5-3  434     NaN  24.5-3            A
80    Krefeld_1966_034_39-3  444     NaN    39-3            A

                                       6       7      8       9    \
0   Querschnittswerte - Section properties     NaN    NaN     NaN
1                                     b\nb  bw\nbw   h\nh  hf\nhf
2                                      NaN     NaN    NaN     NaN
3                                       mm      mm     mm      mm
4                                    127,0   127,0  254,0     NaN
..                                     ...     ...    ...     ...
76                                   254,0   254,0  508,0     NaN
77                                   254,0   254,0  508,0     NaN
78                                   254,0   254,0  508,0     NaN
79                                   254,0   254,0  508,0     NaN
80                                   254,0   254,0  508,0     NaN

               10   ...               118       119            120      121  \
0              NaN  ...               NaN       NaN            NaN      NaN
1   hh,top\nhh,top  ...  fcm,cyl\nfcm_cyl  fck\nfck  f´c\nfc_prime  Vct_ACI
2              NaN  ...  fcm,cyl\nfcm_cyl  fck\nfck  f´c\nfc_prime  Vct_ACI
3               mm  ...               MPa       MPa            MPa       kN
4              NaN  ...              41,5      37,5           39,1    26,82
..             ...  ...               ...       ...            ...      ...
76             NaN  ...              30,4      26,4           28,0   101,75
77             NaN  ...              41,8      37,8           39,4   120,66
78             NaN  ...              15,7      11,7           13,3    70,17
79             NaN  ...              35,4      31,4           33,0   110,51
80             NaN  ...              42,7      38,7           40,3   122,02

       122        123       124       125       126       127
0      NaN        NaN       NaN       NaN       NaN       NaN
1   Vs_ACI  Vcal_sACI  Vmax_ACI  rat_smax  VACI_cal  gmod_ACI
2   Vs_ACI  Vcal_sACI  Vmax_ACI  rat_smax  VACI_cal  gmod_ACI
3       kN         kN        kN       NaN        kN       NaN
4    41,06      67,88    134,08     0,506     67,88      1286
..     ...        ...       ...       ...       ...       ...
76   47,02     148,77    508,74     0,292    148,77      1109
77   47,02     167,67    603,28     0,278    167,67      1398
78   47,02     117,19    350,85     0,334    117,19      1279
79   59,91     170,42    552,56     0,308    170,42      1365
80   78,05     200,07    610,10     0,328    200,07      1198

[81 rows x 127 columns]>

In [157]:
data_mod = data[4:]

In [158]:
data_mod.head()

,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
4,Ahmad_1996_003_NNW-3,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286
5,Ahmad_1996_006_NHW-3,22,Xie;,NHW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"100,2","96,2","97,8","41,32","41,06","82,39","206,62","0,399","82,39",1245
6,Ahmad_1996_007_NHW-3a,23,Yu (1996),NHW-3a,A,"127,0","127,0","254,0",NaN,NaN,...,"91,8","87,8","89,4","39,51","53,38","92,89","197,53","0,470","92,89",1168
7,Ahmad_1996_008_NHW-3b,24,NaN,NHW-3b,A,"127,0","127,0","254,0",NaN,NaN,...,"105,3","101,3","102,9","42,38","64,05","106,44","211,92","0,502","106,44",1154
8,Ahmad_1996_009_NHW-4,25,NaN,NHW-4,A,"127,0","127,0","254,0",NaN,NaN,...,"100,8","96,8","98,4","41,45","41,06","82,51","207,26","0,398","82,51",1140

[Dummy Variables & One Hot Encoding]("https://medium.com/@subashdhoni86/dummy-variables-one-hot-encoding-ebf4f0391a2")

In [159]:
dummies_authors = pd.get_dummies(data_mod[[1]])

In [160]:
dummies_authors

,1_Ahmad_1996_003_NNW-3,1_Ahmad_1996_006_NHW-3,1_Ahmad_1996_007_NHW-3a,1_Ahmad_1996_008_NHW-3b,1_Ahmad_1996_009_NHW-4,1_Angelakos_1999_001_DB0.530M,1_Angelakos_1999_004_DB140M,1_Aparicio_1997_001_VHA,1_Aparicio_1997_002_HA-45,1_Bhal_1968_001_B1S,...,1_Krefeld_1966_010_26-1,1_Krefeld_1966_012_29b-1,1_Krefeld_1966_015_29a-2,1_Krefeld_1966_016_29b-2,1_Krefeld_1966_017_29c-2,1_Krefeld_1966_018_29d-2,1_Krefeld_1966_020_29f-2,1_Krefeld_1966_021_29g-2,1_Krefeld_1966_024_24.5-3,1_Krefeld_1966_034_39-3
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
77,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
78,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
79,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
80,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [161]:
data_mod[[1]].size

77

In [162]:
data_mod[[1]].info

<bound method DataFrame.info of                           1
4      Ahmad_1996_003_NNW-3
5      Ahmad_1996_006_NHW-3
6     Ahmad_1996_007_NHW-3a
7     Ahmad_1996_008_NHW-3b
8      Ahmad_1996_009_NHW-4
..                      ...
76   Krefeld_1966_018_29d-2
77   Krefeld_1966_020_29f-2
78   Krefeld_1966_021_29g-2
79  Krefeld_1966_024_24.5-3
80    Krefeld_1966_034_39-3

[77 rows x 1 columns]>

In [163]:
author_list = data_mod[1].values.tolist()

In [164]:
np_unique_authors = pd.unique(author_list)
#np_unique_authors

/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/3550273074.py:1: FutureWarning: unique with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  np_unique_authors = pd.unique(author_list)

In [165]:
df_new = data_mod

In [185]:
#https://stackoverflow.com/questions/50258960/how-to-apply-labelencoder-for-a-specific-column-in-pandas-dataframe
le = preprocessing.LabelEncoder()
df_new[1] = le.fit_transform(df_new[1].values)
df_new

/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/2036814185.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[1] = le.fit_transform(df_new[1].values)

,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
4,0,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286
5,1,22,Xie;,NHW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"100,2","96,2","97,8","41,32","41,06","82,39","206,62","0,399","82,39",1245
6,2,23,Yu (1996),NHW-3a,A,"127,0","127,0","254,0",NaN,NaN,...,"91,8","87,8","89,4","39,51","53,38","92,89","197,53","0,470","92,89",1168
7,3,24,NaN,NHW-3b,A,"127,0","127,0","254,0",NaN,NaN,...,"105,3","101,3","102,9","42,38","64,05","106,44","211,92","0,502","106,44",1154
8,4,25,NaN,NHW-4,A,"127,0","127,0","254,0",NaN,NaN,...,"100,8","96,8","98,4","41,45","41,06","82,51","207,26","0,398","82,51",1140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,72,428,NaN,29d-2,A,"254,0","254,0","508,0",NaN,NaN,...,"30,4","26,4","28,0","101,75","47,02","148,77","508,74","0,292","148,77",1109
77,73,430,NaN,29f-2,A,"254,0","254,0","508,0",NaN,NaN,...,"41,8","37,8","39,4","120,66","47,02","167,67","603,28","0,278","167,67",1398
78,74,431,NaN,29g-2,A,"254,0","254,0","508,0",NaN,NaN,...,"15,7","11,7","13,3","70,17","47,02","117,19","350,85","0,334","117,19",1279
79,75,434,NaN,24.5-3,A,"254,0","254,0","508,0",NaN,NaN,...,"35,4","31,4","33,0","110,51","59,91","170,42","552,56","0,308","170,42",1365
80,76,444,NaN,39-3,A,"254,0","254,0","508,0",NaN,NaN,...,"42,7","38,7","40,3","122,02","78,05","200,07","610,10","0,328","200,07",1198

In [169]:
df_new[df_new[1]=="Ahmad_1996_003_NNW-3"][1] = 0
df_new[df_new[1]=="Ahmad_1996_003_NNW-3"]

/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1006960178.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]=="Ahmad_1996_003_NNW-3"][1] = 0

,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
4,Ahmad_1996_003_NNW-3,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286

In [176]:
df_author = data_mod
df_author[df_author[1][df_author[1]=="Ahmad_1996_003_NNW-3"] = author_list["Ahmad_1996_003_NNW-3"]]
df_author

SyntaxError: cannot assign to subscript here. Maybe you meant '==' instead of '='? (3938436278.py, line 2)

In [166]:
author_dict = {k:author_list.index(k) for k in author_list }
#df_new[1] = 
for header in author_dict.keys():
    df_new[df_new[1]==header][header] = author_dict[header]
df_new

/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[df_new[1]==header][header] = author_dict[header]
/var/folders/3f/rcgzynbs7s93glm_6gx5m5r80000gn/T/ipykernel_22971/1967531181.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
4,Ahmad_1996_003_NNW-3,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286
5,Ahmad_1996_006_NHW-3,22,Xie;,NHW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"100,2","96,2","97,8","41,32","41,06","82,39","206,62","0,399","82,39",1245
6,Ahmad_1996_007_NHW-3a,23,Yu (1996),NHW-3a,A,"127,0","127,0","254,0",NaN,NaN,...,"91,8","87,8","89,4","39,51","53,38","92,89","197,53","0,470","92,89",1168
7,Ahmad_1996_008_NHW-3b,24,NaN,NHW-3b,A,"127,0","127,0","254,0",NaN,NaN,...,"105,3","101,3","102,9","42,38","64,05","106,44","211,92","0,502","106,44",1154
8,Ahmad_1996_009_NHW-4,25,NaN,NHW-4,A,"127,0","127,0","254,0",NaN,NaN,...,"100,8","96,8","98,4","41,45","41,06","82,51","207,26","0,398","82,51",1140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,Krefeld_1966_018_29d-2,428,NaN,29d-2,A,"254,0","254,0","508,0",NaN,NaN,...,"30,4","26,4","28,0","101,75","47,02","148,77","508,74","0,292","148,77",1109
77,Krefeld_1966_020_29f-2,430,NaN,29f-2,A,"254,0","254,0","508,0",NaN,NaN,...,"41,8","37,8","39,4","120,66","47,02","167,67","603,28","0,278","167,67",1398
78,Krefeld_1966_021_29g-2,431,NaN,29g-2,A,"254,0","254,0","508,0",NaN,NaN,...,"15,7","11,7","13,3","70,17","47,02","117,19","350,85","0,334","117,19",1279
79,Krefeld_1966_024_24.5-3,434,NaN,24.5-3,A,"254,0","254,0","508,0",NaN,NaN,...,"35,4","31,4","33,0","110,51","59,91","170,42","552,56","0,308","170,42",1365
80,Krefeld_1966_034_39-3,444,NaN,39-3,A,"254,0","254,0","508,0",NaN,NaN,...,"42,7","38,7","40,3","122,02","78,05","200,07","610,10","0,328","200,07",1198

In [86]:
# np_mod = np.array(data_mod)
# np_mod

In [87]:
# np_mod2 = np_mod[:,3:]
# np_mod2

In [140]:
# X= data_mod.values
# ct = ColumnTransformer([('1', OneHotEncoder(), [0])], remainder="passthrough")
# ct

ValueError: DataFrame constructor not properly called!

In [ ]:
df_new[df_new[1]=='Ahmad_1996_003_NNW-3'] = 0
df_new

In [132]:
def myOHE(df, header):
    df_list = df[header].values.tolist()
    myDict = {k:df_list.index(k) for k in df_list }
    #print (myDict)
    df_new = df
    df_new[df_new[1]]
    #for i,row in enumerate(df_list):
        #change = df_new.iloc[i][header]
        #change = df_new[header].iloc[i]
        #print(change)
        #change = df_list.index(change)
        #print(change)
    return df_new

In [133]:
myOHE(data_mod, 1)

{'Ahmad_1996_003_NNW-3': 0, 'Ahmad_1996_006_NHW-3': 1, 'Ahmad_1996_007_NHW-3a': 2, 'Ahmad_1996_008_NHW-3b': 3, 'Ahmad_1996_009_NHW-4': 4, 'Angelakos_1999_001_DB0.530M': 5, 'Angelakos_1999_004_DB140M': 6, 'Aparicio_1997_001_VHA': 7, 'Aparicio_1997_002_HA-45': 8, 'Bhal_1968_001_B1S': 9, 'Bhal_1968_002_B2S': 10, 'Bhal_1968_003_B3S': 11, 'Bhal_1968_004_B4S': 12, 'Bresler_1963_001_A-1': 13, 'Bresler_1963_007_C-1': 14, 'Cladera_2002_010_H 100/2': 15, 'Cederwall_1974_003_734-46': 16, 'Guidi_1963_001_V': 17, 'Guralnik_1960_004_IB-2R': 18, 'Guralnik_1960_005_IC-1R': 19, 'Guralnik_1960_006_IC-2R': 20, 'Guralnik_1960_008_ID-2R': 21, 'Hamadi_1976_002_GT-2': 22, 'Hamadi_1976_004_GT-4': 23, 'Hamadi_1976_005_GT-5': 24, 'Hegger_2001_001_SVB 3b': 25, 'Hegger_2003_001_NSC 3L': 26, 'Hegger_2003_002_NSC 3R': 27, 'Johnson_1989_001_1': 28, 'Johnson_1989_002_2': 29, 'Johnson_1989_005_5': 30, 'Kong_1997_001_S1-1': 31, 'Kong_1997_002_S1-2': 32, 'Kong_1997_003_S1-3': 33, 'Kong_1997_004_S1-4': 34, 'Kong_1997_005_S1-5': 35, 'Kong_1997_006_S1-6': 36, 'Kong_1997_007_S2-1': 37, 'Kong_1997_008_S2-2': 38, 'Kong_1997_009_S2-3': 39, 'Kong_1997_010_S2-4': 40, 'Kong_1997_011_S2-5': 41, 'Kong_1997_013_S3-1': 42, 'Kong_1997_014_S3-2': 43, 'Kong_1997_015_S3-3': 44, 'Kong_1997_016_S3-4': 45, 'Kong_1997_017_S3-5': 46, 'Kong_1997_018_S3-6': 47, 'Kong_1997_019_S4-1': 48, 'Kong_1997_021_S4-3': 49, 'Kong_1997_022_S4-4': 50, 'Kong_1997_024_S4-6': 51, 'Kong_1997_025_S5-1': 52, 'Kong_1997_026_S5-2': 53, 'Kong_1997_027_S5-3': 54, 'Kong_1997_031_S7-1': 55, 'Kong_1997_032_S7-2': 56, 'Kong_1997_033_S7-3': 57, 'Kong_1997_034_S7-4': 58, 'Kong_1997_035_S7-5': 59, 'Kong_1997_036_S7-6': 60, 'Kong_1997_037_S8-1': 61, 'Kong_1997_038_S8-2': 62, 'Kong_1997_039_S8-3': 63, 'Kong_1997_040_S8-4': 64, 'Kong_1997_041_S8-5': 65, 'Kong_1997_042_S8-6': 66, 'Krefeld_1966_010_26-1': 67, 'Krefeld_1966_012_29b-1': 68, 'Krefeld_1966_015_29a-2': 69, 'Krefeld_1966_016_29b-2': 70, 'Krefeld_1966_017_29c-2': 71, 'Krefeld_1966_018_29d-2': 72, 'Krefeld_1966_020_29f-2': 73, 'Krefeld_1966_021_29g-2': 74, 'Krefeld_1966_024_24.5-3': 75, 'Krefeld_1966_034_39-3': 76}

,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
4,Ahmad_1996_003_NNW-3,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286
5,Ahmad_1996_006_NHW-3,22,Xie;,NHW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"100,2","96,2","97,8","41,32","41,06","82,39","206,62","0,399","82,39",1245
6,Ahmad_1996_007_NHW-3a,23,Yu (1996),NHW-3a,A,"127,0","127,0","254,0",NaN,NaN,...,"91,8","87,8","89,4","39,51","53,38","92,89","197,53","0,470","92,89",1168
7,Ahmad_1996_008_NHW-3b,24,NaN,NHW-3b,A,"127,0","127,0","254,0",NaN,NaN,...,"105,3","101,3","102,9","42,38","64,05","106,44","211,92","0,502","106,44",1154
8,Ahmad_1996_009_NHW-4,25,NaN,NHW-4,A,"127,0","127,0","254,0",NaN,NaN,...,"100,8","96,8","98,4","41,45","41,06","82,51","207,26","0,398","82,51",1140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,Krefeld_1966_018_29d-2,428,NaN,29d-2,A,"254,0","254,0","508,0",NaN,NaN,...,"30,4","26,4","28,0","101,75","47,02","148,77","508,74","0,292","148,77",1109
77,Krefeld_1966_020_29f-2,430,NaN,29f-2,A,"254,0","254,0","508,0",NaN,NaN,...,"41,8","37,8","39,4","120,66","47,02","167,67","603,28","0,278","167,67",1398
78,Krefeld_1966_021_29g-2,431,NaN,29g-2,A,"254,0","254,0","508,0",NaN,NaN,...,"15,7","11,7","13,3","70,17","47,02","117,19","350,85","0,334","117,19",1279
79,Krefeld_1966_024_24.5-3,434,NaN,24.5-3,A,"254,0","254,0","508,0",NaN,NaN,...,"35,4","31,4","33,0","110,51","59,91","170,42","552,56","0,308","170,42",1365
80,Krefeld_1966_034_39-3,444,NaN,39-3,A,"254,0","254,0","508,0",NaN,NaN,...,"42,7","38,7","40,3","122,02","78,05","200,07","610,10","0,328","200,07",1198

In [117]:
for header in author_list[0]:
    i = 0
    ct = ColumnTransformer([header, OneHotEncoder(), [i]])#, remainder=’passthrough’)
    print(data_mod[1].values)
    X = data_mod[1].values
    X = ct.fit_transform(X)
    i+=1
    print (X)

['Ahmad_1996_003_NNW-3' 'Ahmad_1996_006_NHW-3' 'Ahmad_1996_007_NHW-3a'
 'Ahmad_1996_008_NHW-3b' 'Ahmad_1996_009_NHW-4'
 'Angelakos_1999_001_DB0.530M' 'Angelakos_1999_004_DB140M'
 'Aparicio_1997_001_VHA' 'Aparicio_1997_002_HA-45' 'Bhal_1968_001_B1S'
 'Bhal_1968_002_B2S' 'Bhal_1968_003_B3S' 'Bhal_1968_004_B4S'
 'Bresler_1963_001_A-1' 'Bresler_1963_007_C-1' 'Cladera_2002_010_H 100/2'
 'Cederwall_1974_003_734-46' 'Guidi_1963_001_V' 'Guralnik_1960_004_IB-2R'
 'Guralnik_1960_005_IC-1R' 'Guralnik_1960_006_IC-2R'
 'Guralnik_1960_008_ID-2R' 'Hamadi_1976_002_GT-2' 'Hamadi_1976_004_GT-4'
 'Hamadi_1976_005_GT-5' 'Hegger_2001_001_SVB 3b' 'Hegger_2003_001_NSC 3L'
 'Hegger_2003_002_NSC 3R' 'Johnson_1989_001_1' 'Johnson_1989_002_2'
 'Johnson_1989_005_5' 'Kong_1997_001_S1-1' 'Kong_1997_002_S1-2'
 'Kong_1997_003_S1-3' 'Kong_1997_004_S1-4' 'Kong_1997_005_S1-5'
 'Kong_1997_006_S1-6' 'Kong_1997_007_S2-1' 'Kong_1997_008_S2-2'
 'Kong_1997_009_S2-3' 'Kong_1997_010_S2-4' 'Kong_1997_011_S2-5'
 'Kong_1997_013_S3-1' 'Kong_1997_014_S3-2' 'Kong_1997_015_S3-3'
 'Kong_1997_016_S3-4' 'Kong_1997_017_S3-5' 'Kong_1997_018_S3-6'
 'Kong_1997_019_S4-1' 'Kong_1997_021_S4-3' 'Kong_1997_022_S4-4'
 'Kong_1997_024_S4-6' 'Kong_1997_025_S5-1' 'Kong_1997_026_S5-2'
 'Kong_1997_027_S5-3' 'Kong_1997_031_S7-1' 'Kong_1997_032_S7-2'
 'Kong_1997_033_S7-3' 'Kong_1997_034_S7-4' 'Kong_1997_035_S7-5'
 'Kong_1997_036_S7-6' 'Kong_1997_037_S8-1' 'Kong_1997_038_S8-2'
 'Kong_1997_039_S8-3' 'Kong_1997_040_S8-4' 'Kong_1997_041_S8-5'
 'Kong_1997_042_S8-6' 'Krefeld_1966_010_26-1' 'Krefeld_1966_012_29b-1'
 'Krefeld_1966_015_29a-2' 'Krefeld_1966_016_29b-2'
 'Krefeld_1966_017_29c-2' 'Krefeld_1966_018_29d-2'
 'Krefeld_1966_020_29f-2' 'Krefeld_1966_021_29g-2'
 'Krefeld_1966_024_24.5-3' 'Krefeld_1966_034_39-3']

TypeError: 'OneHotEncoder' object is not iterable

In [98]:
data_mod[1] = data_mod[1][author_dict[data_mod[1]]]

TypeError: unhashable type: 'Series'

In [25]:
scaler = StandardScaler()
standardized_features = scaler.fit_transform(data_mod)

n_components = 2
pca = PCA(n_components=n_components)
principal_components = pca.fit_transform(standardized_features)
pc_df = pd.DataFrame(data=principal_components, columns=[f'PC{i+1}' for i in range(n_components)])

plt.figure(figsize=(8,6))
plt.scatter(pc_df['PC1'], pc_df['PC2'])
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA of Dataset')
plt.show()

explained_variance = pca.explained_variance_ratio_
print(f'Explained variance by component: {explained_variance}')

ValueError: could not convert string to float: 'Ahmad_1996_003_NNW-3'