In [20]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
data = pd.read_excel("preliminary.xlsx")
data.head()

,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
0,NaN,Nr.,Lit.,Bez.,Einheiten E,Querschnittswerte - Section properties,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,b\nb,bw\nbw,h\nh,hf\nhf,"hh,top\nhh,top",...,"fcm,cyl\nfcm_cyl",fck\nfck,f´c\nfc_prime,Vct_ACI,Vs_ACI,Vcal_sACI,Vmax_ACI,rat_smax,VACI_cal,gmod_ACI
2,author,Nr.,Lit.,Bez.,Einheiten E,NaN,NaN,NaN,NaN,NaN,...,"fcm,cyl\nfcm_cyl",fck\nfck,f´c\nfc_prime,Vct_ACI,Vs_ACI,Vcal_sACI,Vmax_ACI,rat_smax,VACI_cal,gmod_ACI
3,NaN,-,-,-,SI / A,mm,mm,mm,mm,mm,...,MPa,MPa,MPa,kN,kN,kN,kN,NaN,kN,NaN
4,Ahmad_1996_003_NNW-3,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286

In [9]:
data.info

<bound method DataFrame.info of                         1    2       3       4            5    \
0                       NaN  Nr.    Lit.    Bez.  Einheiten E
1                       NaN  NaN     NaN     NaN          NaN
2                    author  Nr.    Lit.    Bez.  Einheiten E
3                       NaN    -       -       -       SI / A
4      Ahmad_1996_003_NNW-3   19  Ahmad;   NNW-3            A
..                      ...  ...     ...     ...          ...
76   Krefeld_1966_018_29d-2  428     NaN   29d-2            A
77   Krefeld_1966_020_29f-2  430     NaN   29f-2            A
78   Krefeld_1966_021_29g-2  431     NaN   29g-2            A
79  Krefeld_1966_024_24.5-3  434     NaN  24.5-3            A
80    Krefeld_1966_034_39-3  444     NaN    39-3            A

                                       6       7      8       9    \
0   Querschnittswerte - Section properties     NaN    NaN     NaN
1                                     b\nb  bw\nbw   h\nh  hf\nhf
2                                      NaN     NaN    NaN     NaN
3                                       mm      mm     mm      mm
4                                    127,0   127,0  254,0     NaN
..                                     ...     ...    ...     ...
76                                   254,0   254,0  508,0     NaN
77                                   254,0   254,0  508,0     NaN
78                                   254,0   254,0  508,0     NaN
79                                   254,0   254,0  508,0     NaN
80                                   254,0   254,0  508,0     NaN

               10   ...               118       119            120      121  \
0              NaN  ...               NaN       NaN            NaN      NaN
1   hh,top\nhh,top  ...  fcm,cyl\nfcm_cyl  fck\nfck  f´c\nfc_prime  Vct_ACI
2              NaN  ...  fcm,cyl\nfcm_cyl  fck\nfck  f´c\nfc_prime  Vct_ACI
3               mm  ...               MPa       MPa            MPa       kN
4              NaN  ...              41,5      37,5           39,1    26,82
..             ...  ...               ...       ...            ...      ...
76             NaN  ...              30,4      26,4           28,0   101,75
77             NaN  ...              41,8      37,8           39,4   120,66
78             NaN  ...              15,7      11,7           13,3    70,17
79             NaN  ...              35,4      31,4           33,0   110,51
80             NaN  ...              42,7      38,7           40,3   122,02

       122        123       124       125       126       127
0      NaN        NaN       NaN       NaN       NaN       NaN
1   Vs_ACI  Vcal_sACI  Vmax_ACI  rat_smax  VACI_cal  gmod_ACI
2   Vs_ACI  Vcal_sACI  Vmax_ACI  rat_smax  VACI_cal  gmod_ACI
3       kN         kN        kN       NaN        kN       NaN
4    41,06      67,88    134,08     0,506     67,88      1286
..     ...        ...       ...       ...       ...       ...
76   47,02     148,77    508,74     0,292    148,77      1109
77   47,02     167,67    603,28     0,278    167,67      1398
78   47,02     117,19    350,85     0,334    117,19      1279
79   59,91     170,42    552,56     0,308    170,42      1365
80   78,05     200,07    610,10     0,328    200,07      1198

[81 rows x 127 columns]>

In [17]:
data.iloc?
# header = data.iloc?
# header

Type:        property
String form: <property object at 0x121f51030>
Docstring:
Purely integer-location based indexing for selection by position.

.. deprecated:: 2.2.0

   Returning a tuple from a callable is deprecated.

``.iloc[]`` is primarily integer position based (from ``0`` to
``length-1`` of the axis), but may also be used with a boolean
array.

Allowed inputs are:

- An integer, e.g. ``5``.
- A list or array of integers, e.g. ``[4, 3, 0]``.
- A slice object with ints, e.g. ``1:7``.
- A boolean array.
- A ``callable`` function with one argument (the calling Series or
  DataFrame) and that returns valid output for indexing (one of the above).
  This is useful in method chains, when you don't have a reference to the
  calling object, but would like to base your selection on
  some value.
- A tuple of row and column indexes. The tuple elements consist of one of the
  above inputs, e.g. ``(0, 1)``.

``.iloc`` will raise ``IndexError`` if a requested indexer is
out-of-bounds, except *slice* indexers which allow out-of-bounds
indexing (this conforms with python/numpy *slice* semantics).

See more at :ref:`Selection by Position <indexing.integer>`.

See Also
--------
DataFrame.iat : Fast integer location scalar accessor.
DataFrame.loc : Purely label-location based indexer for selection by label.
Series.iloc : Purely integer-location based indexing for
               selection by position.

Examples
--------
>>> mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
...           {'a': 100, 'b': 200, 'c': 300, 'd': 400},
...           {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000}]
>>> df = pd.DataFrame(mydict)
>>> df
      a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

**Indexing just the rows**

With a scalar integer.

>>> type(df.iloc[0])
<class 'pandas.core.series.Series'>
>>> df.iloc[0]
a    1
b    2
c    3
d    4
Name: 0, dtype: int64

With a list of integers.

>>> df.iloc[[0]]
   a  b  c  d
0  1  2  3  4
>>> type(df.iloc[[0]])
<class 'pandas.core.frame.DataFrame'>

>>> df.iloc[[0, 1]]
     a    b    c    d
0    1    2    3    4
1  100  200  300  400

With a `slice` object.

>>> df.iloc[:3]
      a     b     c     d
0     1     2     3     4
1   100   200   300   400
2  1000  2000  3000  4000

With a boolean mask the same length as the index.

>>> df.iloc[[True, False, True]]
      a     b     c     d
0     1     2     3     4
2  1000  2000  3000  4000

With a callable, useful in method chains. The `x` passed
to the ``lambda`` is the DataFrame being sliced. This selects
the rows whose index label even.

>>> df.iloc[lambda x: x.index % 2 == 0]
      a     b     c     d
0     1     2     3     4
2  1000  2000  3000  4000

**Indexing both axes**

You can mix the indexer types for the index and columns. Use ``:`` to
select the entire axis.

With scalar integers.

>>> df.iloc[0, 1]
2

With lists of integers.

>>> df.iloc[[0, 2], [1, 3]]
      b     d
0     2     4
2  2000  4000

With `slice` objects.

>>> df.iloc[1:3, 0:3]
      a     b     c
1   100   200   300
2  1000  2000  3000

With a boolean array whose length matches the columns.

>>> df.iloc[:, [True, False, True, False]]
      a     c
0     1     3
1   100   300
2  1000  3000

With a callable function that expects the Series or DataFrame.

>>> df.iloc[:, lambda df: [0, 2]]
      a     c
0     1     3
1   100   300
2  1000  3000

In [19]:
data.loc[2]

1           author
2              Nr.
3             Lit.
4             Bez.
5      Einheiten E
          ...
123      Vcal_sACI
124       Vmax_ACI
125       rat_smax
126       VACI_cal
127       gmod_ACI
Name: 2, Length: 127, dtype: object

In [23]:
data_mod = data[4:]

In [24]:
data_mod.head()

,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
4,Ahmad_1996_003_NNW-3,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286
5,Ahmad_1996_006_NHW-3,22,Xie;,NHW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"100,2","96,2","97,8","41,32","41,06","82,39","206,62","0,399","82,39",1245
6,Ahmad_1996_007_NHW-3a,23,Yu (1996),NHW-3a,A,"127,0","127,0","254,0",NaN,NaN,...,"91,8","87,8","89,4","39,51","53,38","92,89","197,53","0,470","92,89",1168
7,Ahmad_1996_008_NHW-3b,24,NaN,NHW-3b,A,"127,0","127,0","254,0",NaN,NaN,...,"105,3","101,3","102,9","42,38","64,05","106,44","211,92","0,502","106,44",1154
8,Ahmad_1996_009_NHW-4,25,NaN,NHW-4,A,"127,0","127,0","254,0",NaN,NaN,...,"100,8","96,8","98,4","41,45","41,06","82,51","207,26","0,398","82,51",1140

In [31]:
data_mod.loc?

Type:        property
String form: <property object at 0x121f51080>
Docstring:
Access a group of rows and columns by label(s) or a boolean array.

``.loc[]`` is primarily label based, but may also be used with a
boolean array.

Allowed inputs are:

- A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
  interpreted as a *label* of the index, and **never** as an
  integer position along the index).
- A list or array of labels, e.g. ``['a', 'b', 'c']``.
- A slice object with labels, e.g. ``'a':'f'``.

  .. warning:: Note that contrary to usual python slices, **both** the
      start and the stop are included

- A boolean array of the same length as the axis being sliced,
  e.g. ``[True, False, True]``.
- An alignable boolean Series. The index of the key will be aligned before
  masking.
- An alignable Index. The Index of the returned selection will be the input.
- A ``callable`` function with one argument (the calling Series or
  DataFrame) and that returns valid output for indexing (one of the above)

See more at :ref:`Selection by Label <indexing.label>`.

Raises
------
KeyError
    If any items are not found.
IndexingError
    If an indexed key is passed and its index is unalignable to the frame index.

See Also
--------
DataFrame.at : Access a single value for a row/column label pair.
DataFrame.iloc : Access group of rows and columns by integer position(s).
DataFrame.xs : Returns a cross-section (row(s) or column(s)) from the
               Series/DataFrame.
Series.loc : Access group of values using labels.

Examples
--------
**Getting values**

>>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
...                   index=['cobra', 'viper', 'sidewinder'],
...                   columns=['max_speed', 'shield'])
>>> df
            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

Single label. Note this returns the row as a Series.

>>> df.loc['viper']
max_speed    4
shield       5
Name: viper, dtype: int64

List of labels. Note using ``[[]]`` returns a DataFrame.

>>> df.loc[['viper', 'sidewinder']]
            max_speed  shield
viper               4       5
sidewinder          7       8

Single label for row and column

>>> df.loc['cobra', 'shield']
2

Slice with labels for row and single label for column. As mentioned
above, note that both the start and stop of the slice are included.

>>> df.loc['cobra':'viper', 'max_speed']
cobra    1
viper    4
Name: max_speed, dtype: int64

Boolean list with the same length as the row axis

>>> df.loc[[False, False, True]]
            max_speed  shield
sidewinder          7       8

Alignable boolean Series:

>>> df.loc[pd.Series([False, True, False],
...                  index=['viper', 'sidewinder', 'cobra'])]
                     max_speed  shield
sidewinder          7       8

Index (same behavior as ``df.reindex``)

>>> df.loc[pd.Index(["cobra", "viper"], name="foo")]
       max_speed  shield
foo
cobra          1       2
viper          4       5

Conditional that returns a boolean Series

>>> df.loc[df['shield'] > 6]
            max_speed  shield
sidewinder          7       8

Conditional that returns a boolean Series with column labels specified

>>> df.loc[df['shield'] > 6, ['max_speed']]
            max_speed
sidewinder          7

Multiple conditional using ``&`` that returns a boolean Series

>>> df.loc[(df['max_speed'] > 1) & (df['shield'] < 8)]
            max_speed  shield
viper          4       5

Multiple conditional using ``|`` that returns a boolean Series

>>> df.loc[(df['max_speed'] > 4) | (df['shield'] < 5)]
            max_speed  shield
cobra               1       2
sidewinder          7       8

Please ensure that each condition is wrapped in parentheses ``()``.
See the :ref:`user guide<indexing.boolean>`
for more details and explanations of Boolean indexing.

.. note::
    If you find yourself using 3 or more conditionals in ``.loc[]``,
    consider using :ref:`advanced indexing<advanced.advanced_hierarchical>`.

    See below for using ``.loc[]`` on MultiIndex DataFrames.

Callable that returns a boolean Series

>>> df.loc[lambda df: df['shield'] == 8]
            max_speed  shield
sidewinder          7       8

**Setting values**

Set value for all items matching the list of labels

>>> df.loc[['viper', 'sidewinder'], ['shield']] = 50
>>> df
            max_speed  shield
cobra               1       2
viper               4      50
sidewinder          7      50

Set value for an entire row

>>> df.loc['cobra'] = 10
>>> df
            max_speed  shield
cobra              10      10
viper               4      50
sidewinder          7      50

Set value for an entire column

>>> df.loc[:, 'max_speed'] = 30
>>> df
            max_speed  shield
cobra              30      10
viper              30      50
sidewinder         30      50

Set value for rows matching callable condition

>>> df.loc[df['shield'] > 35] = 0
>>> df
            max_speed  shield
cobra              30      10
viper               0       0
sidewinder          0       0

Add value matching location

>>> df.loc["viper", "shield"] += 5
>>> df
            max_speed  shield
cobra              30      10
viper               0       5
sidewinder          0       0

Setting using a ``Series`` or a ``DataFrame`` sets the values matching the
index labels, not the index positions.

>>> shuffled_df = df.loc[["viper", "cobra", "sidewinder"]]
>>> df.loc[:] += shuffled_df
>>> df
            max_speed  shield
cobra              60      20
viper               0      10
sidewinder          0       0

**Getting values on a DataFrame with an index that has integer labels**

Another example using integers for the index

>>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
...                   index=[7, 8, 9], columns=['max_speed', 'shield'])
>>> df
   max_speed  shield
7          1       2
8          4       5
9          7       8

Slice with integer labels for rows. As mentioned above, note that both
the start and stop of the slice are included.

>>> df.loc[7:9]
   max_speed  shield
7          1       2
8          4       5
9          7       8

**Getting values with a MultiIndex**

A number of examples using a DataFrame with a MultiIndex

>>> tuples = [
...     ('cobra', 'mark i'), ('cobra', 'mark ii'),
...     ('sidewinder', 'mark i'), ('sidewinder', 'mark ii'),
...     ('viper', 'mark ii'), ('viper', 'mark iii')
... ]
>>> index = pd.MultiIndex.from_tuples(tuples)
>>> values = [[12, 2], [0, 4], [10, 20],
...           [1, 4], [7, 1], [16, 36]]
>>> df = pd.DataFrame(values, columns=['max_speed', 'shield'], index=index)
>>> df
                     max_speed  shield
cobra      mark i           12       2
           mark ii           0       4
sidewinder mark i           10      20
           mark ii           1       4
viper      mark ii           7       1
           mark iii         16      36

Single label. Note this returns a DataFrame with a single index.

>>> df.loc['cobra']
         max_speed  shield
mark i          12       2
mark ii          0       4

Single index tuple. Note this returns a Series.

>>> df.loc[('cobra', 'mark ii')]
max_speed    0
shield       4
Name: (cobra, mark ii), dtype: int64

Single label for row and column. Similar to passing in a tuple, this
returns a Series.

>>> df.loc['cobra', 'mark i']
max_speed    12
shield        2
Name: (cobra, mark i), dtype: int64

Single tuple. Note using ``[[]]`` returns a DataFrame.

>>> df.loc[[('cobra', 'mark ii')]]
               max_speed  shield
cobra mark ii          0       4

Single tuple for the index with a single label for the column

>>> df.loc[('cobra', 'mark i'), 'shield']
2

Slice from index tuple to single label

>>> df.loc[('cobra', 'mark i'):'viper']
                     max_speed  shield
cobra      mark i           12       2
           mark ii           0       4
sidewinder mark i           10      20
           mark ii           1       4
viper      mark ii           7       1
           mark iii         16      36

Slice from index tuple to index tuple

>>> df.loc[('cobra', 'mark i'):('viper', 'mark ii')]
                    max_speed  shield
cobra      mark i          12       2
           mark ii          0       4
sidewinder mark i          10      20
           mark ii          1       4
viper      mark ii          7       1

Please see the :ref:`user guide<advanced.advanced_hierarchical>`
for more details and explanations of advanced indexing.

In [33]:
np_mod = np.array(data_mod)
np_mod

array([['Ahmad_1996_003_NNW-3', 19, 'Ahmad;', ..., '0,506', '67,88',
        1286],
       ['Ahmad_1996_006_NHW-3', 22, 'Xie;', ..., '0,399', '82,39', 1245],
       ['Ahmad_1996_007_NHW-3a', 23, 'Yu (1996)', ..., '0,470', '92,89',
        1168],
       ...,
       ['Krefeld_1966_021_29g-2', 431, nan, ..., '0,334', '117,19', 1279],
       ['Krefeld_1966_024_24.5-3', 434, nan, ..., '0,308', '170,42',
        1365],
       ['Krefeld_1966_034_39-3', 444, nan, ..., '0,328', '200,07', 1198]],
      dtype=object)

In [36]:
np_mod2 = np_mod[:,3:]
np_mod2

array([['NNW-3', 'A', '127,0', ..., '0,506', '67,88', 1286],
       ['NHW-3', 'A', '127,0', ..., '0,399', '82,39', 1245],
       ['NHW-3a', 'A', '127,0', ..., '0,470', '92,89', 1168],
       ...,
       ['29g-2', 'A', '254,0', ..., '0,334', '117,19', 1279],
       ['24.5-3', 'A', '254,0', ..., '0,308', '170,42', 1365],
       ['39-3', 'A', '254,0', ..., '0,328', '200,07', 1198]], dtype=object)

In [32]:
data_mod2 = data_mod.loc[4]
data_mod2.head()

,1,2,3,4,5,6,7,8,9,10,...,118,119,120,121,122,123,124,125,126,127
4,Ahmad_1996_003_NNW-3,19,Ahmad;,NNW-3,A,"127,0","127,0","254,0",NaN,NaN,...,"41,5","37,5","39,1","26,82","41,06","67,88","134,08","0,506","67,88",1286

In [25]:
scaler = StandardScaler()
standardized_features = scaler.fit_transform(data_mod)

n_components = 2
pca = PCA(n_components=n_components)
principal_components = pca.fit_transform(standardized_features)
pc_df = pd.DataFrame(data=principal_components, columns=[f'PC{i+1}' for i in range(n_components)])

plt.figure(figsize=(8,6))
plt.scatter(pc_df['PC1'], pc_df['PC2'])
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA of Dataset')
plt.show()

explained_variance = pca.explained_variance_ratio_
print(f'Explained variance by component: {explained_variance}')

ValueError: could not convert string to float: 'Ahmad_1996_003_NNW-3'